---
pdns_install_repo: "{{ pdns_auth_powerdns_repo_42 }}"
pdns_config:
  master: yes
  slave: no
  local-address: 192.168.53.53
  local-port: 5353
pdns_backends:
  gmysql:
    host: 127.0.0.1
    port: 3306
    user: powerdns
    password: cmwN3skuTRAZr5Z8gwwjUwt725pfZshz
    dbname: pdns
pdns_mysql_databases_credentials:
  gmysql:
    priv_user: "{{ mysql_root_username }}"
    priv_password: "{{ mysql_root_password }}"
    priv_host:
      - "127.0.0.1"
